# Generated by Django 5.0 on 2023-12-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
